# -*- coding: utf-8 -*-
"""password_generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQjeAtBHU4g3QfmEBe_Ui4HtVnmP0DWo
"""

# importing the string lib function

import string as s

from random import *               #imports the random module

chc = s.ascii_letters+s.digits+s.punctuation                              #choice=chc
password= "".join(choice(chc) for x in range (randint(7,18)))

print("NEW PASSWORD is:", password)

chc = s.ascii_letters+s.digits+s.punctuation                              #choice=chc
password= "".join(choice(chc) for x in range (randint(4,8)))

print("NEW PASSWORD is:", password)

chc = s.ascii_letters+s.digits+s.punctuation                              #choice=chc
password= "".join(choice(chc) for x in range (randint(5,16)))

print("NEW PASSWORD is:", password)

chc = s.ascii_letters+s.digits+s.punctuation                              #choice=chc
password= "".join(choice(chc) for x in range (randint(1,16)))

print("NEW PASSWORD is:", password)
